export default {
  name: "DDrawer",
  className: "dDrawer",
  headerClassName: "header",
  footerClassName: "footer",
  titleClassName: "title",
  closeButtonClassName: "closeButton",
  contentClassName: "content",
  defaultTarget: "body",
  defaultRole: "complementary",
  defaultContentRole: "navigation",
  defaultZIndex: 1001,
  defaultWidth: "25%",
  defaultHeight: "25%",
  closeButtonContent: "⛌",
} as const;
