import * as config from "@darwin-studio/ui-codegen/config.json";
import log, { LOG_TYPE } from "@darwin-studio/ui-codegen/src/utils/log";
import generateConstantsFile from "@darwin-studio/ui-codegen/src/utils/generateConstantsFile";
import type { DesignTokens } from "@darwin-studio/ui-codegen/src/types";
import getNakedName from "@darwin-studio/ui-codegen/src/utils/getNakedName";
import { SIZE } from "../../dist/constants/size";

export default async () => {
  // TODO: move to helpers ???
  let designTokens: DesignTokens;
  try {
    designTokens = await import(config.DESIGN_TOKENS_SOURCE);
  } catch {
    log("Can't import design tokens from DESIGN_TOKENS_SOURCE. Check config.json", LOG_TYPE.ERROR);
    return;
  }

  // TODO: add header: dont' edit, autogenerated

  /* TODO: collect size and colorScheme to filter them from the others */
  const colorSchemeTokenConfig = config.TOKENS.COLOR_SCHEME;
  await generateConstantsFile(
    designTokens[colorSchemeTokenConfig.NAME],
    colorSchemeTokenConfig,
    // TODO: move to config ???
    (designTokenNames: string[]) => designTokenNames.filter(
      designTokenName => {
        const isIgnored = (colorSchemeTokenConfig.IGNORE || []).some(ignoredSubstring => {
          return designTokenName.includes(ignoredSubstring);
        })
        return !designTokenName.includes('-') && !isIgnored
      }
    ),
    // TODO: combine filter and transformer ???
    null
  );

  const fontTokenConfig = config.TOKENS.FONT;
  await generateConstantsFile(designTokens[fontTokenConfig.NAME], fontTokenConfig, null, null);

  const sizeTokenConfig = config.TOKENS.SIZE;
  await generateConstantsFile(
    designTokens[sizeTokenConfig.NAME],
    sizeTokenConfig,
    (designTokenNames: string[]) => designTokenNames.filter(
      designTokenName => {
        const isIgnored = (sizeTokenConfig.IGNORE || []).some(ignoredSubstring => {
          return designTokenName.includes(ignoredSubstring);
        })
        return !designTokenName.includes('-') && !isIgnored
      }
    ),
    null
  );

  // TODO: should be generated base on current SIZE
  const paddingTokenConfig = config.TOKENS.PADDING;
  await generateConstantsFile(
    designTokens[paddingTokenConfig.NAME],
    paddingTokenConfig,
    null,
    (designTokenNames: string[]) => designTokenNames.reduce((acc: string[], tokenName) => {
      const { nakedVariantName } = getNakedName(tokenName, Object.values(SIZE))

      if (!acc.find(item => item === nakedVariantName)) {
        acc.push(nakedVariantName);
      }

      return acc
    }, []) // TODO: move to config ??? add util ???
  );

  const roundingTokenConfig = config.TOKENS.ROUNDING;
  await generateConstantsFile(designTokens[roundingTokenConfig.NAME], roundingTokenConfig, null, null);

  const transitionTokenConfig = config.TOKENS.TRANSITION;
  await generateConstantsFile(designTokens[transitionTokenConfig.NAME], transitionTokenConfig, null, null, true);

  const breakpointTokenConfig = config.TOKENS.BREAKPOINT;
  await generateConstantsFile(designTokens[breakpointTokenConfig.NAME], breakpointTokenConfig, null, null, true);
}

