import { mount, shallowMount } from "@vue/test-utils";
import { baseClassCase } from "@darwin-studio/vue-ui/src/utils/test-case-factories";
import { SIZE } from "@darwin-studio/vue-ui-codegen/dist/constants/size";
import { FONT } from "@darwin-studio/vue-ui-codegen/dist/constants/font";
import { DTabs, DTab, DTabpanel } from "./index";
import config from "./config";

// TODO: move to the config
jest.mock("chalk", () => ({
  greenBright: jest.fn(),
  red: jest.fn(),
  yellowBright: jest.fn(),
}));

describe("DTabs", () => {
  const wrapper = mount(DTabs);

  baseClassCase(wrapper, config.tabsClassName);

  it("Should render config.tablistClassName to the tablist's class name", () => {
    const tablist = wrapper.find(`.${config.tablistClassName}`);
    expect(tablist).toBeTruthy();
  });

  it("Should render props.tablistLabel to the tablist's aria-label attr", async () => {
    const tablistLabel = "Some aria label";
    await wrapper.setProps({ tablistLabel });
    const tablist = wrapper.find(`.${config.tablistClassName}`);
    expect(tablist.attributes("aria-label")).toBe(tablistLabel);
  });

  it("Should props.tablistClass to the tablist's class name", async () => {
    const tablistClass = "some-tablist-class";
    await wrapper.setProps({ tablistClass });
    const tablist = wrapper.find(`.${config.tablistClassName}`);
    expect(tablist.classes()).toContain(tablistClass);
  });

  // TODO: props.tabs
  it("Should render props.tabs as content of the tablist", async () => {
    const tab0 = <DTab active={true} label={"Tab 1"} />;
    const tab1 = <DTab label={"Tab 2"} />;
    await wrapper.setProps({ tabs: [tab0, tab1] });
    const tablist = wrapper.find(`.${config.tablistClassName}`);
    const tabs = tablist.findAllComponents(DTab);
    expect(tabs?.[0].element).toMatchSnapshot(); // TODO: other way to compare
    expect(tabs?.[1].element).toMatchSnapshot(); // TODO: other way to compare
  });

  // TODO: slots.tabs
  it("Should render slots.tabs as content of the tablist", async () => {
    const tab1 = await shallowMount(DTab);
    const tab2 = await shallowMount(DTab);
    const wrapper = await mount(DTabs, {
      slots: {
        tabs: [tab1, tab2],
      },
    });
    expect(true).toBeFalsy();
  });

  // TODO: props.tabsSize
  it("Should pass props.tabSize as props.size to containing DTab components", async () => {
    const tabSize = SIZE.LARGE;
    const tab = await shallowMount(DTab);
    await wrapper.setProps({ tabSize, tabs: [tab] });
    expect(true).toBeFalsy();
  });

  // TODO: DTab id autogenerate
  it("Should pass autogenerated id to containing DTab components if not passed", async () => {
    expect(true).toBeFalsy();
  });

  // TODO: DTab <-> DTabpanel connection
  it("Should pass DTabpanel's prop.id to the corresponding DTab as prop.tabpanelId", async () => {
    expect(true).toBeFalsy();
  });

  // TODO: props.tabpanels
  it("Should render props.tabpanels as content the list of tabpanels", async () => {
    const tabpanel1 = shallowMount(DTabpanel);
    const tabpanel2 = shallowMount(DTabpanel);
    await wrapper.setProps({ tabs: [tabpanel1, tabpanel2] });
    expect(true).toBeFalsy();
  });

  // TODO: slots.tabpanels
  it("Should render slots.tabs as content of the tablist", async () => {
    const tabpanel1 = shallowMount(DTabpanel);
    const tabpanel2 = shallowMount(DTabpanel);
    const wrapper = await mount(DTabs, {
      slots: {
        tabs: [tabpanel1, tabpanel2],
      },
    });
    expect(true).toBeFalsy();
  });

  // TODO: props.tabpanelsFont
  it("Should pass props.tabpanelsFont as props.font to containing DTabpanel components", async () => {
    const tabpanelsFont = FONT.SMALL;
    const tabpanel = await shallowMount(DTabpanel);
    await wrapper.setProps({ tabpanelsFont, tabs: [tabpanel] });
    expect(true).toBeFalsy();
  });

  // TODO: DTabpanel id autogenerate
  it("Should pass autogenerated id to containing DTabpanel components if not passed", async () => {
    expect(true).toBeFalsy();
  });

  // TODO: DTabpanel <-> DTab connection
  it("Should pass DTab's prop.id to the corresponding DTabpanel as prop.tabId", async () => {
    expect(true).toBeFalsy();
  });

  // Classes and behaviour
  // TODO: props.disabled
  // TODO: props.padding
  // TODO: props.transition
  // TODO: props.tag
  // TODO: props.tablistTag
  // TODO: props.enableHtml

  // TODO: DTab.props
  // active ???
  // TODO: DTab.onClick
  // TODO: DTab.whenClick
  // TODO: DTabpanel.props
  // active ???
});
