export default {
  name: "DDialog",
  className: "dDialog",
  headerClassName: "header",
  titleClassName: "title",
  closeButtonClassName: "closeButton",
  contentClassName: "content",
  footerClassName: "footer",
  footerButtonClassName: "footerButton",
  defaultTarget: "body",
  defaultRole: "dialog",
  defaultZIndex: 1001,
  defaultMinWidth: "25%",
  defaultMaxWidth: "25%",
  defaultMinHeight: "25%",
  defaultMaxHeight: "25%",
  closeButtonContent: "⛌",
  cancelButtonContent: "🛇",
  acceptButtonContent: "🗸",
};
