export const EVENT_NAME = {
  CLICK: "click",
  CHANGE: "change",
  INPUT: "input",
  SUBMIT: "submit",
  LOAD: "load",
  ERROR: "error",
  RESIZE: "resize",
  SCROLL: "scroll",
  CLOSE: "close",
  CANCEL: "cancel",
  ACCEPT: "accept",
  UPDATE_CHECKED: "update:checked",
  UPDATE_VALUE: "update:value",
  UPDATE_SHOW: "update:show",
  KEYUP: "keyup",
} as const;
