export const POSITION_HORIZONTAL = {
  RIGHT: "right",
  LEFT: "left",
} as const;

export const POSITION_VERTICAL = {
  TOP: "top",
  BOTTOM: "bottom",
} as const;

export const POSITION_SEPARATOR = "-";

/** TODO @rename: POSITION -> PLACEMENT ??? **/
export const POSITION = {
  TOP: POSITION_VERTICAL.TOP,
  TOP_RIGHT: `${POSITION_VERTICAL.TOP}${POSITION_SEPARATOR}${POSITION_HORIZONTAL.RIGHT}`,
  RIGHT: POSITION_HORIZONTAL.RIGHT,
  BOTTOM_RIGHT: `${POSITION_VERTICAL.BOTTOM}${POSITION_SEPARATOR}${POSITION_HORIZONTAL.RIGHT}`,
  BOTTOM: POSITION_VERTICAL.BOTTOM,
  BOTTOM_LEFT: `${POSITION_VERTICAL.BOTTOM}${POSITION_SEPARATOR}${POSITION_HORIZONTAL.LEFT}`,
  LEFT: POSITION_HORIZONTAL.LEFT,
  TOP_LEFT: `${POSITION_VERTICAL.TOP}${POSITION_SEPARATOR}${POSITION_HORIZONTAL.LEFT}`,
} as const;

export const POSITION_OPPOSITE = {
  [POSITION.TOP]: POSITION.BOTTOM,
  [POSITION.TOP_RIGHT]: POSITION.BOTTOM_LEFT,
  [POSITION.RIGHT]: POSITION.LEFT,
  [POSITION.BOTTOM_RIGHT]: POSITION.TOP_LEFT,
  [POSITION.BOTTOM]: POSITION.TOP,
  [POSITION.BOTTOM_LEFT]: POSITION.TOP_RIGHT,
  [POSITION.LEFT]: POSITION.RIGHT,
  [POSITION.TOP_LEFT]: POSITION.BOTTOM_RIGHT,
} as const;
