export default {
  name: "DRadio",
  className: "dRadio",
  inputClassName: "input",
  labelClassName: "label",
  labelInnerClassName: "labelInner",
  captionClassName: "caption",
  captionOffset: "0.2em",
  iconContainerClassName: "iconContainer",
  iconContainerBackdropClassName: "iconContainerBackdrop",
  iconClassName: "icon",
  inputRef: "inputRef",
  buttonClass: "button",
  checkMark: "⬤",
};
